name: labhouse_test_task_radio_app
description: "Radio Stations App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # DI
  injectable: ^2.3.2
  get_it: ^7.6.7

  # Network
  dio: ^5.4.0
  retrofit: ^4.0.3

  # Annotations for code generation
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  logger: ^2.0.2+1

  # State management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator:
  build_runner:
  retrofit_generator:
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
